const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

class DownloadService {
  constructor() {
    this.browser = null;
  }

  async initBrowser() {
    if (!this.browser) {
      this.browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });
    }
    return this.browser;
  }

  async closeBrowser() {
    if (this.browser) {
      await this.browser.close();
      this.browser = null;
    }
  }

  generateBlogHTML(blogContent, title = "Generated Blog") {
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${title}</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background: #fff;
            }
            h1 {
                color: #2c3e50;
                border-bottom: 3px solid #3498db;
                padding-bottom: 10px;
                margin-bottom: 30px;
            }
            h2 {
                color: #34495e;
                margin-top: 30px;
                margin-bottom: 15px;
            }
            h3 {
                color: #7f8c8d;
                margin-top: 25px;
                margin-bottom: 10px;
            }
            p {
                margin-bottom: 15px;
                text-align: justify;
            }
            ul, ol {
                margin-bottom: 15px;
                padding-left: 30px;
            }
            li {
                margin-bottom: 5px;
            }
            strong {
                color: #2c3e50;
            }
            em {
                color: #7f8c8d;
            }
            .footer {
                margin-top: 50px;
                padding-top: 20px;
                border-top: 1px solid #bdc3c7;
                text-align: center;
                color: #7f8c8d;
                font-size: 14px;
            }
        </style>
    </head>
    <body>
        ${blogContent}
        <div class="footer">
            <p>Generated by EduExtract - Educational Content Platform</p>
            <p>Generated on: ${new Date().toLocaleDateString()}</p>
        </div>
    </body>
    </html>
    `;
  }

  generateSummaryHTML(summary, title = "Content Summary") {
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${title}</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                line-height: 1.8;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background: #fff;
            }
            h1 {
                color: #2c3e50;
                border-bottom: 3px solid #e74c3c;
                padding-bottom: 10px;
                margin-bottom: 30px;
                text-align: center;
            }
            .summary-content {
                background: #f8f9fa;
                padding: 30px;
                border-radius: 10px;
                border-left: 5px solid #e74c3c;
                margin: 20px 0;
            }
            .footer {
                margin-top: 50px;
                padding-top: 20px;
                border-top: 1px solid #bdc3c7;
                text-align: center;
                color: #7f8c8d;
                font-size: 14px;
            }
        </style>
    </head>
    <body>
        <h1>${title}</h1>
        <div class="summary-content">
            ${summary.replace(/\n/g, '<br>')}
        </div>
        <div class="footer">
            <p>Generated by EduExtract - Educational Content Platform</p>
            <p>Generated on: ${new Date().toLocaleDateString()}</p>
        </div>
    </body>
    </html>
    `;
  }

  generateQuizHTML(quiz, title = "Quiz") {
    let html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${title}</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background: #fff;
            }
            h1 {
                color: #2c3e50;
                border-bottom: 3px solid #f39c12;
                padding-bottom: 10px;
                margin-bottom: 30px;
                text-align: center;
            }
            .question {
                background: #f8f9fa;
                padding: 20px;
                margin: 20px 0;
                border-radius: 10px;
                border-left: 5px solid #f39c12;
            }
            .question-number {
                font-weight: bold;
                color: #f39c12;
                margin-bottom: 10px;
            }
            .options {
                margin: 10px 0;
            }
            .option {
                margin: 5px 0;
                padding-left: 20px;
            }
            .correct-answer {
                background: #d4edda;
                padding: 10px;
                border-radius: 5px;
                margin-top: 10px;
                border-left: 3px solid #28a745;
            }
            .footer {
                margin-top: 50px;
                padding-top: 20px;
                border-top: 1px solid #bdc3c7;
                text-align: center;
                color: #7f8c8d;
                font-size: 14px;
            }
        </style>
    </head>
    <body>
        <h1>${title}</h1>
    `;

    quiz.forEach((q, index) => {
      html += `
        <div class="question">
            <div class="question-number">Question ${index + 1}:</div>
            <div class="question-text">${q.question}</div>
            <div class="options">
      `;
      
      q.options.forEach((option, optIndex) => {
        const isCorrect = optIndex === q.correctAnswer;
        html += `
          <div class="option ${isCorrect ? 'correct-answer' : ''}">
            ${String.fromCharCode(65 + optIndex)}. ${option}
            ${isCorrect ? ' ✓' : ''}
          </div>
        `;
      });
      
      html += `
            </div>
        </div>
      `;
    });

    html += `
        <div class="footer">
            <p>Generated by EduExtract - Educational Content Platform</p>
            <p>Generated on: ${new Date().toLocaleDateString()}</p>
        </div>
    </body>
    </html>
    `;

    return html;
  }

  generateFlashcardsHTML(flashcards, title = "Flashcards") {
    let html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${title}</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background: #fff;
            }
            h1 {
                color: #2c3e50;
                border-bottom: 3px solid #9b59b6;
                padding-bottom: 10px;
                margin-bottom: 30px;
                text-align: center;
            }
            .flashcard {
                background: #f8f9fa;
                padding: 20px;
                margin: 20px 0;
                border-radius: 10px;
                border-left: 5px solid #9b59b6;
                page-break-inside: avoid;
            }
            .flashcard-number {
                font-weight: bold;
                color: #9b59b6;
                margin-bottom: 10px;
            }
            .question {
                font-weight: bold;
                margin-bottom: 15px;
                color: #2c3e50;
            }
            .answer {
                color: #7f8c8d;
                font-style: italic;
            }
            .footer {
                margin-top: 50px;
                padding-top: 20px;
                border-top: 1px solid #bdc3c7;
                text-align: center;
                color: #7f8c8d;
                font-size: 14px;
            }
        </style>
    </head>
    <body>
        <h1>${title}</h1>
    `;

    flashcards.forEach((card, index) => {
      html += `
        <div class="flashcard">
            <div class="flashcard-number">Card ${index + 1}:</div>
            <div class="question">Q: ${card.question}</div>
            <div class="answer">A: ${card.answer}</div>
        </div>
      `;
    });

    html += `
        <div class="footer">
            <p>Generated by EduExtract - Educational Content Platform</p>
            <p>Generated on: ${new Date().toLocaleDateString()}</p>
        </div>
    </body>
    </html>
    `;

    return html;
  }

  async generatePDF(htmlContent, filename) {
    const browser = await this.initBrowser();
    const page = await browser.newPage();
    
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '20mm',
        bottom: '20mm',
        left: '20mm'
      }
    });
    
    await page.close();
    return pdfBuffer;
  }

  async downloadBlog(blogContent, title = "Generated Blog") {
    const html = this.generateBlogHTML(blogContent, title);
    return await this.generatePDF(html, `${title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
  }

  async downloadSummary(summary, title = "Content Summary") {
    const html = this.generateSummaryHTML(summary, title);
    return await this.generatePDF(html, `${title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
  }

  async downloadQuiz(quiz, title = "Quiz") {
    const html = this.generateQuizHTML(quiz, title);
    return await this.generatePDF(html, `${title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
  }

  async downloadFlashcards(flashcards, title = "Flashcards") {
    const html = this.generateFlashcardsHTML(flashcards, title);
    return await this.generatePDF(html, `${title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
  }
}

module.exports = new DownloadService();
