const mongoose = require('mongoose');

const marketplaceContentSchema = new mongoose.Schema({
  // Reference to the original content (if it was generated by the app)
  contentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'GeneratedContent',
    required: false // Optional because users can upload personal content
  },
  
  // Creator information
  creatorId: {
    type: String,
    required: true,
    ref: 'User'
  },
  
  // Content metadata
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 200
  },
  
  description: {
    type: String,
    required: true,
    trim: true,
    maxlength: 1000
  },
  
  // Content categorization
  category: {
    type: String,
    required: true,
    enum: ['mathematics', 'science', 'history', 'literature', 'languages', 'arts', 'technology', 'business', 'health', 'other']
  },
  
  subject: {
    type: String,
    required: true,
    trim: true,
    maxlength: 100
  },
  
  difficulty: {
    type: String,
    required: true,
    enum: ['beginner', 'intermediate', 'advanced']
  },
  
  tags: [{
    type: String,
    trim: true,
    maxlength: 50
  }],
  
  // Content details
  contentType: {
    type: String,
    required: true,
    enum: ['blog', 'slides', 'flashcards', 'quiz', 'summary', 'personal']
  },
  
  isPersonal: {
    type: Boolean,
    required: true,
    default: false
  },
  
  // Content data (can be text, structured data, or file reference)
  contentData: {
    type: mongoose.Schema.Types.Mixed,
    required: false
  },
  
  // File upload information
  filePath: {
    type: String,
    required: false
  },
  
  // Preview content for free users
  previewContent: {
    type: mongoose.Schema.Types.Mixed,
    required: false
  },
  
  // File information (if content includes files)
  fileUrl: {
    type: String,
    required: false
  },
  
  fileType: {
    type: String,
    required: false
  },
  
  fileSize: {
    type: Number,
    required: false
  },
  
  // Pricing (0 = free, >0 = paid)
  price: {
    type: Number,
    required: true,
    default: 0,
    min: 0
  },
  
  // Currency (default to USD)
  currency: {
    type: String,
    required: true,
    default: 'USD',
    enum: ['USD', 'EUR', 'GBP', 'INR']
  },
  
  // Plagiarism detection results
  plagiarismScore: {
    type: Number,
    required: false,
    min: 0,
    max: 100
  },
  
  plagiarismReport: {
    type: mongoose.Schema.Types.Mixed,
    required: false
  },
  
  // Content status
  status: {
    type: String,
    required: true,
    enum: ['pending', 'approved', 'rejected', 'flagged'],
    default: 'pending'
  },
  
  // Engagement metrics
  views: {
    type: Number,
    default: 0
  },
  
  likes: {
    type: Number,
    default: 0
  },
  
  downloads: {
    type: Number,
    default: 0
  },
  
  // User interactions
  likedBy: [{
    type: String,
    ref: 'User'
  }],
  
  savedBy: [{
    type: String,
    ref: 'User'
  }],
  
  // Timestamps
  createdAt: {
    type: Date,
    default: Date.now
  },
  
  updatedAt: {
    type: Date,
    default: Date.now
  },
  
  // Approval information
  approvedAt: {
    type: Date,
    required: false
  },
  
  approvedBy: {
    type: String,
    required: false,
    ref: 'User'
  }
});

// Add indexes for better query performance
marketplaceContentSchema.index({ category: 1, subject: 1 });
marketplaceContentSchema.index({ creatorId: 1 });
marketplaceContentSchema.index({ status: 1 });
marketplaceContentSchema.index({ createdAt: -1 });
marketplaceContentSchema.index({ views: -1 });
marketplaceContentSchema.index({ likes: -1 });
marketplaceContentSchema.index({ price: 1 });

// Update the updatedAt field before saving
marketplaceContentSchema.pre('save', function(next) {
  this.updatedAt = new Date();
  next();
});

// Virtual for average rating (we'll implement this later)
marketplaceContentSchema.virtual('averageRating').get(function() {
  // This will be populated when we add reviews
  return 0;
});

// Ensure virtual fields are serialized
marketplaceContentSchema.set('toJSON', { virtuals: true });
marketplaceContentSchema.set('toObject', { virtuals: true });

module.exports = mongoose.model('MarketplaceContent', marketplaceContentSchema);
