const mongoose = require('mongoose');

const payoutSchema = new mongoose.Schema({
  // Payout details
  payoutId: {
    type: String,
    required: false, // Will be generated by pre-save hook
    unique: true
  },
  
  // Seller information (Firebase UID string, not ObjectId)
  sellerId: {
    type: String,
    required: true
  },
  
  // Amount details
  totalAmount: {
    type: Number,
    required: true,
    min: 0
  },
  
  currency: {
    type: String,
    required: true,
    default: 'USD'
  },
  
  // Payout method
  payoutMethod: {
    type: String,
    required: true,
    enum: ['bank_transfer', 'paypal', 'stripe_connect', 'manual'],
    default: 'manual'
  },
  
  // Payout status
  status: {
    type: String,
    required: true,
    enum: ['pending', 'approved', 'processing', 'completed', 'rejected', 'cancelled'],
    default: 'pending'
  },
  
  // Related purchases
  purchaseIds: [{
    type: String,
    ref: 'Purchase'
  }],
  
  // Payment processor details
  transactionId: {
    type: String,
    required: false
  },
  
  // Bank/Payment details (encrypted or stored securely)
  payoutDetails: {
    accountNumber: String,
    routingNumber: String,
    accountHolderName: String,
    bankName: String,
    paypalEmail: String,
    stripeAccountId: String
  },
  
  // Admin actions
  requestedAt: {
    type: Date,
    default: Date.now
  },
  
  approvedAt: {
    type: Date,
    required: false
  },
  
  approvedBy: {
    type: String,
    required: false
  },
  
  processedAt: {
    type: Date,
    required: false
  },
  
  completedAt: {
    type: Date,
    required: false
  },
  
  rejectionReason: {
    type: String,
    required: false,
    maxlength: 500
  },
  
  // Notes
  notes: {
    type: String,
    required: false,
    maxlength: 1000
  },
  
  // Timestamps
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

  // Add indexes
payoutSchema.index({ sellerId: 1 });
payoutSchema.index({ status: 1 });
payoutSchema.index({ requestedAt: -1 });
// Note: payoutId already has unique: true which creates an index, so we don't need to add it again

// Update the updatedAt field before saving
payoutSchema.pre('save', function(next) {
  this.updatedAt = new Date();
  next();
});

// Generate unique payout ID
payoutSchema.pre('save', function(next) {
  if (!this.payoutId) {
    this.payoutId = 'PAYOUT_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
  }
  next();
});

module.exports = mongoose.model('Payout', payoutSchema);

