const mongoose = require('mongoose');

const purchaseSchema = new mongoose.Schema({
  // Purchase details
  purchaseId: {
    type: String,
    required: false, // Will be generated by pre-save hook
    unique: true
  },
  
  // Content being purchased
  contentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'MarketplaceContent',
    required: true
  },
  
  // Buyer information
  buyerId: {
    type: String,
    required: true,
    ref: 'User'
  },
  
  // Seller information
  sellerId: {
    type: String,
    required: true,
    ref: 'User'
  },
  
  // Payment details
  amount: {
    type: Number,
    required: true,
    min: 0
  },
  
  currency: {
    type: String,
    required: true,
    default: 'USD'
  },
  
  // Commission and earnings
  platformCommission: {
    type: Number,
    required: false,
    default: 0,
    min: 0
  },
  
  commissionRate: {
    type: Number,
    required: false,
    default: 0.15, // 15% default commission
    min: 0,
    max: 1
  },
  
  sellerEarnings: {
    type: Number,
    required: false,
    default: 0,
    min: 0
  },
  
  payoutStatus: {
    type: String,
    required: false,
    enum: ['pending', 'paid', 'processing'],
    default: 'pending'
  },
  
  payoutId: {
    type: String,
    required: false,
    ref: 'Payout'
  },
  
  // Payment method
  paymentMethod: {
    type: String,
    required: true,
    enum: ['credit_card', 'debit_card', 'paypal', 'stripe', 'other']
  },
  
  // Payment status
  paymentStatus: {
    type: String,
    required: true,
    enum: ['pending', 'completed', 'failed', 'refunded'],
    default: 'pending'
  },
  
  // Transaction ID from payment processor
  transactionId: {
    type: String,
    required: false
  },
  
  // Purchase status
  status: {
    type: String,
    required: true,
    enum: ['active', 'expired', 'cancelled'],
    default: 'active'
  },
  
  // Access control
  accessExpiresAt: {
    type: Date,
    required: false // null means lifetime access
  },
  
  // Timestamps
  purchasedAt: {
    type: Date,
    default: Date.now
  },
  
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Add indexes for better query performance
purchaseSchema.index({ buyerId: 1 });
purchaseSchema.index({ contentId: 1 });
purchaseSchema.index({ paymentStatus: 1 });
purchaseSchema.index({ purchasedAt: -1 });
// purchaseId is already indexed due to unique: true constraint

// Update the updatedAt field before saving
purchaseSchema.pre('save', function(next) {
  this.updatedAt = new Date();
  next();
});

// Generate unique purchase ID
purchaseSchema.pre('save', function(next) {
  if (!this.purchaseId) {
    this.purchaseId = 'PURCHASE_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
  }
  next();
});

module.exports = mongoose.model('Purchase', purchaseSchema);
